leftnav:
- identifier: 950eb6d7-df0c-74bc-a441-be1c2b7eadd6
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 761c1cb3-8fdc-e5d1-682c-f14e1a509a52
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 008507df-7305-f656-64ef-3b91feb631f5
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
- identifier: cf3dfae0-ab9d-1601-3b23-54c8406e0d06
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 40
- identifier: d9abb33b-c8ca-504d-6925-bfb215f6ada4
  name: Exams
  pageRef: /pages/exams
  weight: 50
